---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: tag
  image: rancher/dapper:v0.4.2
  commands:
    - echo "${DRONE_TAG}-amd64" | sed -e 's/+/-/g' >.tags
  volumes:
    - name: docker
      path: /var/run/docker.sock
- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    build_args:
      - ARCH=amd64
      - TAG=${DRONE_TAG}
    password:
      from_secret: docker_password
    repo: "rancher/rke2-upgrade"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: s390x

platform:
  os: linux
  arch: amd64

node:
  arch: s390x

steps:
- name: tag
  image: rancher/dapper:v0.5.8
  failure: ignore
  commands:
    - echo "${DRONE_TAG}-s390x" | sed -e 's/+/-/g' >.tags
  volumes:
    - name: docker
      path: /var/run/docker.sock
- name: docker-publish
  image: rancher/drone-images:docker-s390x
  failure: ignore
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    dockerfile: Dockerfile
    build_args:
      - ARCH=s390x
      - TAG=${DRONE_TAG}
    password:
      from_secret: docker_password
    repo: "rancher/rke2-upgrade"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
  - name: manifest
    image: plugins/docker
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    settings:
      dry_run: true
      dockerfile: Dockerfile.manifest
      repo: "rancher/rke2-upgrade-manifest"
      build_args_from_env:
        - DOCKER_USERNAME
        - DOCKER_PASSWORD
        - DRONE_TAG
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

depends_on:
  - amd64
  - s390x
