#!/bin/bash
# Configure the shell to exit immediately if a command exits with a non-zero
# status (-e) or if any command in a pipeline fails (-o pipefail).
set -eo pipefail
set -x

source $(dirname $0)/version

cd $(dirname $0)/..

# This script serves to download/stage the installer

mkdir -p artifacts

if [ -z "${LOCAL_ARTIFACTS}" ]; then
    curl -fL https://raw.githubusercontent.com/rancher/rke2/master/install.sh > artifacts/installer.sh
    chmod +x artifacts/installer.sh

    if [[ "${ARCH}" = "arm64" ]] && [[ "${VERSION}" =~ ^v1\.(20|24|25|26)\. ]]; then
        echo "Skipping arm64 - not supported for this version."
        exit
    fi

    pushd artifacts
    if [ -n "${PRIME_RIBS}" ]; then
        curl -fL -O -R https://${PRIME_RIBS}/rke2/${URI_VERSION}/rke2.linux-${ARCH}.tar.gz
        curl -fL -O -R https://${PRIME_RIBS}/rke2/${URI_VERSION}/sha256sum-${ARCH}.txt
    else
      curl -fL -O -R https://github.com/rancher/rke2/releases/download/${URI_VERSION}/rke2.linux-${ARCH}.tar.gz
      curl -fL -O -R https://github.com/rancher/rke2/releases/download/${URI_VERSION}/sha256sum-${ARCH}.txt
    fi
    popd
else
    cp local/* artifacts
    chmod +x artifacts/installer.sh
fi

pushd artifacts
grep "rke2.linux-${ARCH}.tar.gz$" "sha256sum-${ARCH}.txt" | sha256sum -c -
popd
