name: CI

on: [repository_dispatch]
jobs:
  CreateATag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Create Release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.client_payload.tag }}
          release_name: Release ${{ github.event.client_payload.tag }}
          draft: false
          prerelease: false
      - run: echo Created Release ${{ github.event.client_payload.tag }}
